import React from "react";
import ReactDOM from "react-dom/client";

/**
 * Header
 *   -Logo
 *   -Nav items
 * Body
 *   -Search
 *   -Restaurant container
 *      -RestaurantCard
 *         -Img
 *         -Name of res, star rating, cuisine
 * Footer
 *   -Copyright
 *   -Links
 *   -Address
 *   -Contact
 */
const Header = () => {
  return (
    <div className="header">
      <div className="logo container">
        <img
          className="logo"
          src="https://st2.depositphotos.com/1351697/8470/v/950/depositphotos_84709916-stock-illustration-food-and-restaurant-logo-design.jpg"
        />
      </div>
      <div className="nav-items">
        <ul>
          <li>Home</li>
          <li>About Us</li>
          <li>Contact Us</li>
          <li>Cart</li>
        </ul>
      </div>
    </div>
  );
};

const RestaurantCard = (props) => {
  const { resData } = props;
  const { cloudinaryImageId, name, cuisines, costForTwoString, avgRating } =
    resData?.data;
  return (
    <div className="res-card">
      <img
        className="res-logo"
        alt="res-logo"
        src={
          "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/" +
          cloudinaryImageId
        }
      />
      <h3>{name}</h3>
      <h4>{cuisines.join(", ")}</h4>
      <h5>{costForTwoString}</h5>
      <h5>{avgRating}</h5>
    </div>
  );
};

const resList = [
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "4320",
      name: "Mehfil",
      uuid: "4dee4970-8673-42b6-8a49-cab0efdb258f",
      city: "3",
      area: "Narayanguda",
      totalRatingsString: "10000+ ratings",
      cloudinaryImageId: "esp0fhddgfgdss5hyhpi",
      cuisines: ["Biryani", "North Indian", "Tandoor", "Chinese", "Kebabs"],
      tags: [],
      costForTwo: 30000,
      costForTwoString: "₹300 FOR TWO",
      deliveryTime: 18,
      minDeliveryTime: 18,
      maxDeliveryTime: 18,
      slaString: "18 MINS",
      lastMileTravel: 1.899999976158142,
      slugs: {
        restaurant: "mehfil-narayanguda-himayath-nagar",
        city: "hyderabad",
      },
      cityState: "3",
      address: "Near Narayanguda Flyover, Narayanguda, Hyderabad",
      locality: "Near Narayanguda Flyover",
      parentId: 637,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      ribbon: [
        {
          type: "PROMOTED",
        },
      ],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 2600,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 2600,
        message: "",
        title: "Delivery Charge",
        amount: "2600",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID:
        "cid=7255387~p=1~eid=00000189-3edb-9bd8-0e89-2ee7005c0134~srvts=1688976727000",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "1.8 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "10% OFF",
        subHeader: "UPTO ₹40",
        discountTag: "",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "4320",
        deliveryTime: 18,
        minDeliveryTime: 18,
        maxDeliveryTime: 18,
        lastMileTravel: 1.899999976158142,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: true,
      avgRating: "3.9",
      totalRatings: 10000,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "615591",
      name: "New Akbar Fast Food",
      uuid: "4bba447e-e79c-4406-98aa-8ef029b8abc3",
      city: "3",
      area: "Mehdipatnam",
      totalRatingsString: "100+ ratings",
      cloudinaryImageId: "fbcejkodnbkfmktbmznf",
      cuisines: ["Indian"],
      tags: [],
      costForTwo: 30000,
      costForTwoString: "₹300 FOR TWO",
      deliveryTime: 36,
      minDeliveryTime: 36,
      maxDeliveryTime: 36,
      slaString: "36 MINS",
      lastMileTravel: 5.699999809265137,
      slugs: {
        restaurant: "new-akbar-fast-food-mehdipatnam-mehdipatnam",
        city: "hyderabad",
      },
      cityState: "3",
      address:
        "Door No: 10-3-14/A, Humayun Nagar, Hyderabad-T.S ,Mehdipatnam Circle No 12,Hyderabad,Telangana-500028",
      locality: "Royal Colony",
      parentId: 367111,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 5200,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 5200,
        message: "",
        title: "Delivery Charge",
        amount: "5200",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 1,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "5.6 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "FREE ITEM",
        subHeader: "",
        discountTag: "",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "615591",
        deliveryTime: 36,
        minDeliveryTime: 36,
        maxDeliveryTime: 36,
        lastMileTravel: 5.699999809265137,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "IT_IS_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "3.4",
      totalRatings: 100,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "696113",
      name: "Red Bucket Biryani",
      uuid: "a8fe7b5c-e9e0-4324-873b-e2fef4d98f59",
      city: "3",
      area: "Amberpet",
      totalRatingsString: "100+ ratings",
      cloudinaryImageId: "be2bfa3b5dde1e71b41144e9b62878a9",
      cuisines: ["Biryani"],
      tags: [],
      costForTwo: 40000,
      costForTwoString: "₹400 FOR TWO",
      deliveryTime: 25,
      minDeliveryTime: 25,
      maxDeliveryTime: 25,
      slaString: "25 MINS",
      lastMileTravel: 4.099999904632568,
      slugs: {
        restaurant: "red-bucket-biryani-himayath-nagar-himayath-nagar-2",
        city: "hyderabad",
      },
      cityState: "3",
      address:
        "H NO 2-3-96 MAIN ROAD OOP MAHANKALI  TEMPLE SRI RAMANA CHOURASTHA  AMBERPET, Amberpet Circle No 16,  Hyderabad, Telangana-500013",
      locality: "96 Main Road",
      parentId: 306664,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 3700,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 3700,
        message: "",
        title: "Delivery Charge",
        amount: "3700",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 1,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "4 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "10% OFF",
        subHeader: "UPTO ₹40",
        discountTag: "",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "696113",
        deliveryTime: 25,
        minDeliveryTime: 25,
        maxDeliveryTime: 25,
        lastMileTravel: 4.099999904632568,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "IT_IS_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "3.6",
      totalRatings: 100,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "704065",
      name: "Tea World",
      uuid: "dc27cb54-6bd7-4366-a64d-0987a4028438",
      city: "3",
      area: "Himayath Nagar",
      totalRatingsString: "Too Few Ratings",
      cloudinaryImageId: "f1ced5a462175b99a73b001fd9a3fdb5",
      cuisines: ["Beverages"],
      tags: [],
      costForTwo: 15000,
      costForTwoString: "₹150 FOR TWO",
      deliveryTime: 30,
      minDeliveryTime: 30,
      maxDeliveryTime: 30,
      slaString: "30 MINS",
      lastMileTravel: 3,
      slugs: {
        restaurant: "tea-world-himayath-nagar-himayath-nagar",
        city: "hyderabad",
      },
      cityState: "3",
      address:
        "H.No 1-1, 379/284/B, Indira Park Rd, P & T Colony, Ashok Nagar, Jawahar Nagar, Hyderabad, Telangana 500020, India",
      locality: "Jawahar Nagar",
      parentId: 277401,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 3700,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 3700,
        message: "",
        title: "Delivery Charge",
        amount: "3700",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "3 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "50% OFF",
        subHeader: "UPTO ₹100",
        discountTag: "",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "704065",
        deliveryTime: 30,
        minDeliveryTime: 30,
        maxDeliveryTime: 30,
        lastMileTravel: 3,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "--",
      totalRatings: 0,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "8093",
      name: "Akson Restaurant",
      uuid: "0c0a430f-43d4-44f5-a16c-edbabb57c7d2",
      city: "3",
      area: "Punjagutta",
      totalRatingsString: "10000+ ratings",
      cloudinaryImageId: "bl8xukkclvjnxnwqphnw",
      cuisines: ["North Indian", "Biryani", "Kerala"],
      tags: [],
      costForTwo: 25000,
      costForTwoString: "₹250 FOR TWO",
      deliveryTime: 35,
      minDeliveryTime: 35,
      maxDeliveryTime: 35,
      slaString: "35 MINS",
      lastMileTravel: 6.5,
      slugs: {
        restaurant: "akson-restaurant-panjagutta-road-banjara-hills",
        city: "hyderabad",
      },
      cityState: "3",
      address:
        "Akson restaurant, above Manyavar,Sharma Complex, Beside Model House,, Saibaba Temple Rd, Punjagutta, Hyderabad, Telangana 500082, India",
      locality: "Panjagutta Road",
      parentId: 19600,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 6000,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 6000,
        message: "",
        title: "Delivery Charge",
        amount: "6000",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 1,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "6.5 kms",
      hasSurge: false,
      sla: {
        restaurantId: "8093",
        deliveryTime: 35,
        minDeliveryTime: 35,
        maxDeliveryTime: 35,
        lastMileTravel: 6.5,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "IT_IS_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "4.3",
      totalRatings: 10000,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "4138",
      name: "Grand Hotel",
      uuid: "c1a1d888-51b7-4bcc-b539-f884c796a015",
      city: "3",
      area: "Koti",
      totalRatingsString: "10000+ ratings",
      cloudinaryImageId: "g1arzw6qd7g9affkmgzk",
      cuisines: ["Biryani", "Chinese", "Tandoor", "Haleem"],
      tags: [],
      costForTwo: 30000,
      costForTwoString: "₹300 FOR TWO",
      deliveryTime: 21,
      minDeliveryTime: 21,
      maxDeliveryTime: 21,
      slaString: "21 MINS",
      lastMileTravel: 1.2000000476837158,
      slugs: {
        restaurant: "grand-hotel-abids-himayath-nagar",
        city: "hyderabad",
      },
      cityState: "3",
      address: "Opposite Big Bazaar, 4-1-395,Abids Road, Hyderabad",
      locality: "Abids Road",
      parentId: 4001,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      ribbon: [
        {
          type: "PROMOTED",
        },
      ],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 2600,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 2600,
        message: "",
        title: "Delivery Charge",
        amount: "2600",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID:
        "cid=7255392~p=7~eid=00000189-3edb-9bd8-0e89-2ee9005c076e~srvts=1688976727000",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "1.2 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "FREE ITEM",
        subHeader: "",
        discountTag: "",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "4138",
        deliveryTime: 21,
        minDeliveryTime: 21,
        maxDeliveryTime: 21,
        lastMileTravel: 1.2000000476837158,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: true,
      avgRating: "4.1",
      totalRatings: 10000,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "683280",
      name: "Alina wraps",
      uuid: "8ee675c7-79d1-4d77-b946-3d125f14a490",
      city: "3",
      area: "Santoshnagar & Saidabad",
      totalRatingsString: "50+ ratings",
      cloudinaryImageId: "81a2584284cab7ad184a284c7016467e",
      cuisines: ["Burgers", "Grill", "Salads"],
      tags: [],
      costForTwo: 20000,
      costForTwoString: "₹200 FOR TWO",
      deliveryTime: 26,
      minDeliveryTime: 26,
      maxDeliveryTime: 26,
      slaString: "26 MINS",
      lastMileTravel: 4.800000190734863,
      slugs: {
        restaurant:
          "alina-wraps-santoshnagar-&-saidabad-santoshnagar-&-saidabad",
        city: "hyderabad",
      },
      cityState: "3",
      address:
        "9, CRIDA Rd, New Santoshnagar, Santosh Nagar, Hyderabad, Telangana 500059, India",
      locality: "Santosh Nagar",
      parentId: 407769,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 3700,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 3700,
        message: "",
        title: "Delivery Charge",
        amount: "3700",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 1,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "4.8 kms",
      hasSurge: false,
      sla: {
        restaurantId: "683280",
        deliveryTime: 26,
        minDeliveryTime: 26,
        maxDeliveryTime: 26,
        lastMileTravel: 4.800000190734863,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "IT_IS_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "3.3",
      totalRatings: 50,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "503514",
      name: "Isha Snacks",
      uuid: "8986ae23-8fc6-441c-86c6-4ad61306140a",
      city: "3",
      area: "Kothapet & Dilsukhnagar",
      totalRatingsString: "Too Few Ratings",
      cloudinaryImageId: "ng2xo3ypsvwqifntz7zy",
      cuisines: ["Indian"],
      tags: [],
      costForTwo: 20000,
      costForTwoString: "₹200 FOR TWO",
      deliveryTime: 32,
      minDeliveryTime: 32,
      maxDeliveryTime: 32,
      slaString: "32 MINS",
      lastMileTravel: 6.599999904632568,
      slugs: {
        restaurant:
          "isha-snacks-kothapet-&-dilsukhnagar-kothapet-&-dilsukhnagar",
        city: "hyderabad",
      },
      cityState: "3",
      address:
        "2, Ambedkar Nagar, Amdebakar Nagar, Saroornagar, Telangana 500035, India",
      locality: "Saroornagar",
      parentId: 301498,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 6000,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 6000,
        message: "",
        title: "Delivery Charge",
        amount: "6000",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 1,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "6.5 kms",
      hasSurge: false,
      sla: {
        restaurantId: "503514",
        deliveryTime: 32,
        minDeliveryTime: 32,
        maxDeliveryTime: 32,
        lastMileTravel: 6.599999904632568,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "IT_IS_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "--",
      totalRatings: 0,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "624472",
      name: "Leon's - Burgers & Wings (Leon Grill)",
      uuid: "abd90994-858e-455a-aaac-32d43469dcb7",
      city: "3",
      area: "Himayat Nagar",
      totalRatingsString: "1000+ ratings",
      cloudinaryImageId: "jihaeqyqzda0eeno6viq",
      cuisines: ["American", "Snacks", "Turkish", "Portuguese", "Continental"],
      tags: [],
      costForTwo: 30000,
      costForTwoString: "₹300 FOR TWO",
      deliveryTime: 25,
      minDeliveryTime: 25,
      maxDeliveryTime: 25,
      slaString: "25 MINS",
      lastMileTravel: 1.899999976158142,
      slugs: {
        restaurant:
          "leon's---burgers-&-wings-(leon-grill)-himayath-nagar-himayath-nagar",
        city: "hyderabad",
      },
      cityState: "3",
      address:
        "H NO 3 5 899,GROUND FLOOR,NEXT TO NILOUFER CAFE,OLD MLA QUARTERS ROAD,HIMAYAT NAGAR,Hyderabad,Telangana 500028",
      locality: "old Mla Quarters Road",
      parentId: 371281,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      ribbon: [
        {
          type: "PROMOTED",
        },
      ],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 2600,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 2600,
        message: "",
        title: "Delivery Charge",
        amount: "2600",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID:
        "cid=7452563~p=10~eid=00000189-3edb-9bd8-0e89-2eea005c0a28~srvts=1688976727000",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "1.8 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "₹125 OFF",
        subHeader: "ABOVE ₹299",
        discountTag: "FLAT DEAL",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "624472",
        deliveryTime: 25,
        minDeliveryTime: 25,
        maxDeliveryTime: 25,
        lastMileTravel: 1.899999976158142,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: true,
      avgRating: "4.0",
      totalRatings: 1000,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "355747",
      name: "Grameen Kulfi",
      uuid: "bc78eb9e-b256-413f-a60e-ec510f76fefb",
      city: "3",
      area: "Narayanguda",
      totalRatingsString: "1000+ ratings",
      cloudinaryImageId: "mwggy9gmdboqzi7gloms",
      cuisines: ["Ice Cream", "Desserts"],
      tags: [],
      costForTwo: 12000,
      costForTwoString: "₹120 FOR TWO",
      deliveryTime: 18,
      minDeliveryTime: 18,
      maxDeliveryTime: 18,
      slaString: "18 MINS",
      lastMileTravel: 1.600000023841858,
      slugs: {
        restaurant: "grameen-kulfi-kmit-himayath-nagar",
        city: "hyderabad",
      },
      cityState: "3",
      address: "H.no-1-30,Madhapur,Harijan Basti, Hyderabad,Telangan,500084",
      locality: "KMIT",
      parentId: 12175,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 2600,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 2600,
        message: "",
        title: "Delivery Charge",
        amount: "2600",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "1.6 kms",
      hasSurge: false,
      sla: {
        restaurantId: "355747",
        deliveryTime: 18,
        minDeliveryTime: 18,
        maxDeliveryTime: 18,
        lastMileTravel: 1.600000023841858,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "4.6",
      totalRatings: 1000,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "142670",
      name: "Shah Ghouse Cafe & Restaurant",
      uuid: "88b357e6-6560-449b-9400-5e9a9915db66",
      city: "3",
      area: "Lakdikapul",
      totalRatingsString: "10000+ ratings",
      cloudinaryImageId: "bk26jkkqpg55veii0aj9",
      cuisines: ["Biryani", "Chinese", "Tandoor", "Mughlai", "North Indian"],
      tags: [],
      costForTwo: 35000,
      costForTwoString: "₹350 FOR TWO",
      deliveryTime: 37,
      minDeliveryTime: 37,
      maxDeliveryTime: 37,
      slaString: "37 MINS",
      lastMileTravel: 4.199999809265137,
      slugs: {
        restaurant: "shah-ghouse-cafe-restaurant-lakdikapool-nampally",
        city: "hyderabad",
      },
      cityState: "3",
      address: "6-2-971,Lakdikapool,Hyd",
      locality: "Santh Nirankari Satsang Bhavan",
      parentId: 18992,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      ribbon: [
        {
          type: "PROMOTED",
        },
      ],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 3700,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 3700,
        message: "",
        title: "Delivery Charge",
        amount: "3700",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID:
        "cid=7364358~p=13~eid=00000189-3edb-9bd8-0e89-2eeb005c0d6b~srvts=1688976727000",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "4.1 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "20% OFF",
        subHeader: "UPTO ₹50",
        discountTag: "",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "142670",
        deliveryTime: 37,
        minDeliveryTime: 37,
        maxDeliveryTime: 37,
        lastMileTravel: 4.199999809265137,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: true,
      avgRating: "4.1",
      totalRatings: 10000,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "194411",
      name: "Zam Zam Fast Food",
      uuid: "678eb2e9-086c-43d8-8de0-9a0b378c00e5",
      city: "3",
      area: "Moghalpura",
      totalRatingsString: "500+ ratings",
      cloudinaryImageId: "cvx5ldbi8lknxzosssrm",
      cuisines: ["Chinese"],
      tags: [],
      costForTwo: 20000,
      costForTwoString: "₹200 FOR TWO",
      deliveryTime: 36,
      minDeliveryTime: 36,
      maxDeliveryTime: 36,
      slaString: "36 MINS",
      lastMileTravel: 4.5,
      slugs: {
        restaurant: "zam-zam-fast-food-charminar-charminar",
        city: "hyderabad",
      },
      cityState: "3",
      address:
        "Shop 23, Quli Qutub Shah Complex, Opposite Mecca Masjid, Charminar Road, Charminar, Hyderabad,Charminar, Hyderabad,Hyderabad",
      locality: "Charminar",
      parentId: 17529,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 3700,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 3700,
        message: "",
        title: "Delivery Charge",
        amount: "3700",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 1,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "4.5 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "30% OFF",
        subHeader: "UPTO ₹75",
        discountTag: "",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "194411",
        deliveryTime: 36,
        minDeliveryTime: 36,
        maxDeliveryTime: 36,
        lastMileTravel: 4.5,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "IT_IS_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "3.7",
      totalRatings: 500,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "569371",
      name: "Oki Poki - Sushi, Dimsums & More",
      uuid: "1b2b98e1-dcc2-46a9-a842-5e62c641278e",
      city: "3",
      area: "Masab Tank",
      totalRatingsString: "Too Few Ratings",
      cloudinaryImageId: "yembpczggcg3ssmkl8t9",
      cuisines: ["Chinese", "Asian", "Pan-Asian", "Thai", "Oriental"],
      tags: [],
      costForTwo: 120000,
      costForTwoString: "₹1200 FOR TWO",
      deliveryTime: 36,
      minDeliveryTime: 36,
      maxDeliveryTime: 36,
      slaString: "36 MINS",
      lastMileTravel: 5.699999809265137,
      slugs: {
        restaurant: "oki-poki-sushi-dimsums-more-masab-tank-banjara-hills",
        city: "hyderabad",
      },
      cityState: "3",
      address:
        "10/3/311/2/A, NMDC COLONY, VENKATADRI COLONY, MASAB TANK, HYDERABAD",
      locality: "VENKATADRI COLONY",
      parentId: 306310,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 5200,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 5200,
        message: "",
        title: "Delivery Charge",
        amount: "5200",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "5.6 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "60% OFF",
        subHeader: "UPTO ₹120",
        discountTag: "",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "569371",
        deliveryTime: 36,
        minDeliveryTime: 36,
        maxDeliveryTime: 36,
        lastMileTravel: 5.699999809265137,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "--",
      totalRatings: 0,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "369152",
      name: "Pista House Restaurant & Bakery\t",
      uuid: "1f6bcc73-c207-484e-8be8-2f3b1c0a6de8",
      city: "3",
      area: "Malakpet",
      totalRatingsString: "10000+ ratings",
      cloudinaryImageId: "gztlag7iu5911juzggqz",
      cuisines: ["North Indian", "Biryani", "Tandoor", "Chinese"],
      tags: [],
      costForTwo: 30000,
      costForTwoString: "₹300 FOR TWO",
      deliveryTime: 25,
      minDeliveryTime: 25,
      maxDeliveryTime: 25,
      slaString: "25 MINS",
      lastMileTravel: 4.699999809265137,
      slugs: {
        restaurant:
          "pista-house-bakery-&-restaurant-kothapet-&-dilsukhnagar-kothapet-&-dilsukhnagar",
        city: "hyderabad",
      },
      cityState: "3",
      address:
        "AARTHIS SEVEN HILLS COMPLEX PLOT NO 17 TO 24 AND 41 EAST PRASANTH NAGAR ARVIND NAGAR TEEGALAGUDA MUSARAMBAHG  500036",
      locality: "Kothapet ",
      parentId: 319765,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      ribbon: [
        {
          type: "PROMOTED",
        },
      ],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 3700,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 3700,
        message: "",
        title: "Delivery Charge",
        amount: "3700",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID:
        "cid=7364303~p=16~eid=00000189-3edb-9bd8-0e89-2eec005c100f~srvts=1688976727000",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "4.6 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "20% OFF",
        subHeader: "UPTO ₹50",
        discountTag: "",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "369152",
        deliveryTime: 25,
        minDeliveryTime: 25,
        maxDeliveryTime: 25,
        lastMileTravel: 4.699999809265137,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: true,
      avgRating: "4.1",
      totalRatings: 10000,
      new: false,
    },
    subtype: "basic",
  },
];

const Body = () => {
  return (
    <div className="body">
      <div className="search">
        <input type="text" placeholder="search"></input>
        <button>Search</button>
      </div>
      <div className="restaurant-container">
        {resList.map((restaurant) => (
          <RestaurantCard key={restaurant.data.id} resData={restaurant} />
        ))}
        {/*  <RestaurantCard resData={resList[0]} />
       <RestaurantCard resData={resList[1]} />
        <RestaurantCard resData={resList[2]} />
        <RestaurantCard resData={resList[3]} />
        <RestaurantCard resData={resList[4]} />
        <RestaurantCard resData={resList[5]} />
        <RestaurantCard resData={resList[6]} />
        <RestaurantCard resData={resList[7]} />
        <RestaurantCard resData={resList[8]} />
        <RestaurantCard resData={resList[9]} />
        <RestaurantCard resData={resList[10]} />
        <RestaurantCard resData={resList[12]} />
        <RestaurantCard resData={resList[13]} />
        <RestaurantCard resData={resList[14]} /> */}
      </div>
    </div>
  );
};

const Footer = () => {
  return (
    <div className="footer">
      <h3>developed by karuna with❤️</h3>
    </div>
  );
};

const AppLayout = () => {
  return (
    <div className="app">
      <Header />
      <Body />
      <Footer />
    </div>
  );
};

const root = ReactDOM.createRoot(document.getElementById("root"));
root.render(<AppLayout />);
